### ISSUE TITLE
cryptg make bytes mutable

### ISSUE THREAD

**Issue by NotStatilko** [cher-nov/cryptg#10]
That's was really fun to debug. How about to add note about this in docstring?
```python3

from cryptg import encrypt_ige

key, iv, text = b'k'*32, b'iv'*16, b't'*16

print(text) # b'tttttttttttttttt'
encrypt_ige(text,key,iv)
print(text) # b'\x8a\xea7\x9d\xabM\xd1cLO\x98\xf4"\x0b\x05b'
```

**Comment by Lonami** [comment]
Sorry about the "fun" times. This was definitely an issue in 0.2. However, it is no longer an issue in the master branch, so I will close this ticket. Thanks for the report.
