### ISSUE TITLE
Add support to release aarch64 wheels

### ISSUE THREAD

**Issue by odidev** [cher-nov/cryptg#11]
Problem
---------
On aarch64, ‘pip install cryptg’ builds the wheels from source code and then installs it. It requires the user to have a development environment installed on his system. Also, it takes some time to build the wheels than downloading and extracting the wheels from pypi.

Resolution
-----------
On aarch64, ‘pip install cryptg’ should download the wheels from pypi 

@cher-nov, @Team Please let me know your interest in releasing aarch64 wheels. I can help in this.

**Comment by Rongronggg9** [comment]
Now that #12 has been merged, is there a timetable for the next release with aarch64 wheels pushed to PyPI?

**Comment by Lonami** [comment]
I have pushed the aarch64 wheels to PyPi. Let me know if there are any issues.
