### ISSUE TITLE
Nodejs module

### ISSUE THREAD

**Issue by iamDonkey** [cher-nov/cryptg#18]
Can this be ported to a nodejs native module?
If yes please tell me the steps.
Thankyou.

**Comment by iamgabrielsoft** [comment]
Yes it's can

**Comment by iamDonkey** [comment]
> Yes it's can

How? Can you provide me the steps?

**Comment by iamDonkey** [comment]
@iamgabrielsoft ?

**Comment by iamDonkey** [comment]
@Lonami can you help sir?

**Comment by Lonami** [comment]
I do not have plans to port this to NodeJS. This library is mostly intended just for use in Telethon, Python. You're welcome to fork it for other platforms such as web.
