### ISSUE TITLE
Offer more utilities

### ISSUE THREAD

**Issue by Lonami** [cher-nov/cryptg#2]
Such as [`Factorizator`](https://github.com/LonamiWebs/Telethon/blob/master/telethon/crypto/factorization.py), which is also pretty slow. This could be written in C.

**Comment by eos175** [comment]
Hi, i wrote this in c++, regards
https://github.com/eos175/factorization

**Comment by Lonami** [comment]
Sorry for the late response, and thanks for the effort, but now that the library depends on `grammers-cryptg`, it would be trickier to also depend on a C++ component. Also licensing and all that.
