### ISSUE TITLE
Add Cargo.lock to the repo

### ISSUE THREAD

**Issue by K900** [cher-nov/cryptg#20]
Exactly what it says on the tin. Right now it's not really possible to build the repo reproducibly as the dependencies aren't locked, which is a pretty big no-no for distribution packaging.

**Comment by Lonami** [comment]
I guess we're technically building "an end-product" and not a library, even if the end-product is a library (for another language). Given it makes sense as per the book on [Cargo.toml vs Cargo.lock](https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html#cargotoml-vs-cargolock) and it's useful to do, we probably should commit the file.

**Comment by K900** [comment]
Yeah, "no Cargo.lock for libraries" thing is mostly there for the kind of libraries that you'd include in another project, i.e. something that does not produce artifacts by itself. In this case, there is an artifact, namely the Python extension, so I'd say a Cargo.lock makes sense.

**Comment by Lonami** [comment]
Do you need a new version to be published to PyPi, or is this okay?

**Comment by K900** [comment]
A new version would definitely be preferable, but I'm not really in a hurry, if you've got other changes you want to bundle with that.
