### ISSUE TITLE
Support for Python 3.11

### ISSUE THREAD

**Issue by Rongronggg9** [cher-nov/cryptg#24]
https://docs.python.org/3.11/whatsnew/3.11.html

I've tested the existing GHA workflow. It is broken. I may help fix it.

Another problem is dropping Python 3.6 support or not, as PyO3 has dropped it in v0.16.0. If it can be dropped, we can bump PyO3 to its latest version so that adding Python 3.11 support won't be difficult. I may help with it too.

**Comment by Lonami** [comment]
`cryptg` is not *required* to run Telethon, and given that [3.6 has reached EOL](https://peps.python.org/pep-0494/):

> As of 2021-12-23, 3.6 has reached the [end-of-life phase](https://devguide.python.org/devcycle/#end-of-life-branches) of its release cycle

I'm okay with dropping support for it. (Users can still use an older version as there are virtually no functionality changes.)

**Comment by Rongronggg9** [comment]
Sure, I am working on it :)
